### ISSUE TITLE
Problems with wavelength spacing for LTE calculations

### ISSUE THREAD

**Issue by vsadykov** [ITA-Solar/rh#16]
Hello,

There is a problem when some of the atoms are presented in "Passive" (LTE) mode: It seems that RH does not compute the solution for the wavelengths/transitions which belong to atoms in passive mode.
I have tried computations of H and Fe atoms (Fe.33 and Fe.52) keeping H in active mode and Fe in passive. The output wavelength spacing contains H transitions but does not contain Fe transitions/wavelengths.
Also, when both elements are forced to "Passive", the code crashes.

**Comment by tiagopereira** [comment]
This happens by design. Transitions of passive elements are not included unless they overlap in wavelength with the transitions of active atoms. 

For pure LTE calculations (ie, all atoms passive) you need to use the special binary `rh15d_lteray`, and not all output is written. The binaries `rh15d_ray` and `rh15d_ray_pool` require at least one atom to be active.

**Comment by vsadykov** [comment]
Thank you for clarification!)
